[project]
name = "aiida-relax-project"
version = "0.1.0"
description = "Learning workflows for AiiDA + VASP"
requires-python = ">=3.9"
dependencies = [
    "aiida-core",
    "aiida-vasp",
    "ase",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["aiida_relax_project*"]
exclude = ["launch_scripts*", "data_generation*"]
