[project]
name = "aiida-relax-project"
version = "0.1.0"
description = "Learning workflows for AiiDA + VASP/CP2K"
requires-python = ">=3.9"
dependencies = [
    "aiida-core",
    "aiida-vasp",
    "aiida-cp2k",
    "ase",
    "pymatgen",
    "requests",
    "pyyaml",
]

[project.entry-points."aiida.workflows"]
"relax.vasp" = "aiida_relax_project.relax:MyVaspWorkChain"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["aiida_relax_project*"]
exclude = ["launch_scripts*", "data_generation*"]
